spring:
  output.ansi.enabled: always
  profiles:
    active: local
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/doc?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: lldj
    password: lldj1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

  security:
    user:
      name: lldj
      password: lldj1234

logging:
  level:
    root: info
    com.ll.dj: debug
    org.hibernate.type.descriptor.sql: trace