spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/doc?useUnicode=true&characterEncoding=utf8
    username: lldj
    password: lldj1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

  security:
    user:
      name: user
      password: 1111

logging:
  level:
    root: info
    com.ll.dj: debug

server:
  port: 8283

